### ISSUE TITLE
Create UML Class Diagrams

### ISSUE THREAD

**Issue by BetsyRowley** [BetsyRowley/menstrual-tracker#15]
Part 1: Finish the refinement #1

From your collection of sequence diagrams and/or narrations found in refinement #1, create 1 or 2 class diagrams.  

Submission.  The diagrams should be uploaded to your Kanban board...or a link should be shown on your Kanban board. 

All content should be accessible through your Kanban board.  (Even if it is a link to your GitHub/bitbucket project!)

![image](https://github.com/BetsyRowley/menstrual-tracker/assets/21369486/ae202fae-ea3b-493d-a34f-34af6c301a92)

**Comment by BetsyRowley** [comment]
Hey @cklukas16, In order to make sense of classes as I did the refining portion, I started to build out a UML Class Diagram. By no means is it a final draft but it helped me better envision how classes worked together.

If you're interested in adding onto this diagram, here are the steps I took to set this up.

1. In Visual Studio Code -->Extensions --> PlantUML (v2.18.0)
2. Manage PlantUML settings --> search for Plantuml: Server --> set to: https://www.plantuml.com/plantuml
3. Upload the attached file, click on Open Preview to side. [ClassDiagram.md](https://github.com/BetsyRowley/menstrual-tracker/files/14817380/ClassDiagram.md)
4. Make edits to the attached file as needed (Link for syntax: https://plantuml.com/class-diagram)


Happy to walk through this via a call as well.

**Comment by cklukas16** [comment]
@BetsyRowley You're a rockstar!! I got the extension working and can see the diagram. 

What do you think about a class for "calendar" or "month"? I'm thinking the month class would know things like number of days, start DOW, year?, and would hold a list of daily records. Is this superfluous to what we already have? I'm wondering if this would help for display purposes.

**Comment by cklukas16** [comment]
@BetsyRowley Is it more accurate to say that a Cycle is made up of HormonePhases and that each HormonePhase is associated with specific exercises?

**Comment by BetsyRowley** [comment]
@cklukas16 

- I don't think calendar or month would be a necessary class but let's talk through that whenever we talk next. I see the Java 'Date' Class handling all Date related information. For our classes, I envision that each time DailyRecord gets instantiated, a record gets stored in the DB in a Records table and the Date for that record servers as the unique ID - if a record already exists for that date, you cannot add another record for that date, you can only modify or delete it. When Cycle gets instantiated, a cycle record gets stored in the DB in Cycle Table. I haven't figured out how it will get calculated yet but when Cycle get's instantiated, I see it calculating the full cycle as each day passes and that key value pair { "Day 1", 31/MAR/2024} gets stored as part of that cycle record in the db. Again, dates would serve as unique identifiers. Once a new cycle begins, a new cycle records gets added.
- I tried to think of separation of duties for all of the classes (DailyRecord, Cycle, HormonePhase, Exercise, Food). Meaning, the View will make a call to all of those classes to get values based on the date selected. I envisioned HormonePhase, Exercise & Food would reach out to Cycle with a date and say hey, what's the cycle day? Then depending on what the cycle day is, HormonePhase, Exercise & Food return info based on the cycle day.

I'm sure there are several ways to design this so if something makes more sense to you, let's walk through it!

**Comment by cklukas16** [comment]
Makes sense to me. That detail is so helpful. I like the idea of the date
being the unique id. That seems like a really elegant solution to a few
different organizational challenges. We can talk through more in person
this coming weekend.

**Comment by BetsyRowley** [comment]
@cklukas16 class diagram has been updated and new screenshot included in the Description.

[ClassDiagram.md](https://github.com/BetsyRowley/menstrual-tracker/files/15182956/ClassDiagram.md)

**Comment by BetsyRowley** [comment]
@cklukas16 change of heart, I decided to remove the hormone phase and exercise classes. The more I thought about it the less sense it made having that data stored in classes (singletons?).

[ClassDiagram.md](https://github.com/BetsyRowley/menstrual-tracker/files/15182970/ClassDiagram.md)

**Comment by cklukas16** [comment]
@BetsyRowley No worries. I support that decision.

**Comment by BetsyRowley** [comment]
One last update, fixed a few typos
[ClassDiagram.md](https://github.com/BetsyRowley/menstrual-tracker/files/15194499/ClassDiagram.md)
