### ISSUE TITLE
Create General Layout

### ISSUE THREAD

**Issue by BetsyRowley** [BetsyRowley/menstrual-tracker#18]
| HTML Page | Functionality |
| ------------  | -------------- |
| (1) Login Page   | Authentication will be stretch goal, so just start with a Login Button |
| (2) Dashboard | (1) Calendar View: Color Coding for Menstrual Phase, include a Key with brief description of phase and links to resource page (2) Detailed View for day selected on calendar, default for today, include HealthValues if entered already & recommendations |
| (3) Adding/Editing Daily Health Values | When you click on Add or Edit Button from within the Detailed Day view, you can add/edit daily HealthValues |
| (4) Start Cycle | Clicking on the Start Cycle Button from your Dashboard, allows you to select the day you started bleeding, a counter then tracks where you are in the cycle and that number is always present on your Dashboard |
| (5) Resources/Learn More | Static Content, links to external resources |

**Comment by BetsyRowley** [comment]
@cklukas16 I added one more page for Start Cycle. I think it would be best to set this independently from the HealthValues. Let me know if that makes sense for you as well.

**Comment by cklukas16** [comment]
@BetsyRowley This looks good. We can nail this down more specifically as we start implementing. This is enough for me to get the user stories finished.
