### ISSUE TITLE
Create Initial Project Build Out

### ISSUE THREAD

**Issue by BetsyRowley** [BetsyRowley/menstrual-tracker#4]

**Comment by BetsyRowley** [comment]
Great tutorial suggested by Caitlin: https://www.youtube.com/watch?v=UgX5lgv4uVM

**Comment by BetsyRowley** [comment]
Static Content for logic and Dashboard Key: https://uofstthomasmn-my.sharepoint.com/:x:/r/personal/rowl7939_stthomas_edu/_layouts/15/Doc.aspx?sourcedoc=%7B9CCB2903-F146-4F67-A2CC-5D9884A945F2%7D&file=StaticContent.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=rowl7939%40stthomas.edu&ct=1711918078110&wdOrigin=OFFICECOM-WEB.MAIN.EDGEWORTH&cid=c0127ad0-f0ba-463b-a8ec-a63ed92957d2&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=1deab027-66d0-4d75-8851-afc34788b723

**Comment by BetsyRowley** [comment]
@cklukas16 initial code has been added to our repo. I have implemented everything covered in the tutorial through the JDBC / Spring Data section. I don't think it's necessary to implement Production read features for this project. Please let me know if you have any problems running locally.

I think we should have the back end covered pretty much covered for the first three user stories.

**Comment by cklukas16** [comment]
@BetsyRowley Thanks, Betsy! This looks great. I cloned a copy to my machine. I didn't test every endpoint, but the H2 select query and get endpoints worked as expected. I'll do my best to dabble this week. Let's connect during class Thursday to find a time to meet to talk next steps.
